# Generated by Django 5.2.6 on 2025-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock_actual', models.PositiveIntegerField(verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(verbose_name='Stock minimo')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ('nombre', 'categoria', 'precio'),
            },
        ),
    ]
