# Generated by Django 5.2.6 on 2025-09-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock_actual',
            new_name='stock',
        ),
    ]
