<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-27 17:18
=======
# Generated by Django 5.2.6 on 2025-09-25 00:07
>>>>>>> ffe0b7c4dfe7434c728e400f054817282b36e82d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock_actual',
            new_name='stock',
        ),
    ]
