# Generated by Django 5.2.6 on 2025-09-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_rename_stock_actual_producto_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
