# Generated by Django 5.2.6 on 2025-10-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ('nombre',),
            },
        ),
    ]
