# Generated by Django 5.2.6 on 2025-10-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id', 'nombre', 'categoria', 'precio')},
        ),
    ]
