# Generated by Django 5.2.6 on 2025-10-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('id',)},
        ),
    ]
