# Generated by Django 5.2.6 on 2025-10-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_compra_fecha_alter_compra_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 10, 10, 16, 33, 22, 324363), verbose_name='fecha'),
        ),
    ]
