# Generated by Django 5.2.6 on 2025-10-10 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 10, 10, 17, 54, 4, 122685), verbose_name='fecha'),
        ),
    ]
