# Generated by Django 5.2.6 on 2025-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('dirección', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ('nombre', 'email', 'telefono', 'dirección'),
            },
        ),
    ]
